### PR TITLE
playing devil's advocate, surface area reducer

### PR DESCRIPTION
**Pull request by ivanbelenky**

### CODE REVIEW

**Review by dongyuanjushi — CHANGES_REQUESTED** [review]
Could you revise your commit message to describe more clearly about the change you make? Thanks!

**Comment by ivanbelenky** [comment]
Sure! despite the CVE bogus problem, I guess that automatic dependency vulnerability scans is of the essence given the rapid pace that the field and its libraries have. The hook added to the PR direclty checks against [safety-db](https://github.com/pyupio/safety-db) for known vulns.

Output of this hook is all green for the current `requirements.txt`.

Thanks!

**Comment by ivanbelenky** [comment]
@dongyuanjushi if this security checks for dependencies is deemed unnecessary let me know and Ill close the PR

**Comment by dongyuanjushi** [comment]
The dependency check is good. But it is recommended to follow the commit message format in CONTRIBUTE.md so that it can help future maintainance. You can close this and reopen a new pull request with more meaningful commit messages. Thanks for your understanding.

**Comment by ivanbelenky** [comment]
Sure, let me reopen then.

**Pull request closed without merging**
